services:
  caddy:
    image: caddy:2.9-alpine
    restart: unless-stopped
    ports:
      - "6767:6767"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web-penus-network       

volumes:
  caddy_data:
  caddy_config:

networks:
  web-penus-network:
    external: true
